CI almost done.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,54 +2,171 @@ name: CI
 
 on:
   push:
-    branches: [main]
-    paths-ignore:
-      - '**/*.md'
   pull_request:
-    branches: [main]
-
-defaults:
-  run:
-    # See https://github.com/marketplace/actions/setup-miniconda#important
-    shell: bash -el {0}
+  workflow_dispatch:
 
 jobs:
-  validate:
-    strategy:
-      matrix:
-        cppVersion: [17]
+    stir2petsird:
+        runs-on: ubuntu-24.04
+        
+        steps:
+        - name: Install System Dependencies (date-tz)
+          run: |
+            sudo apt-get update
+            sudo apt-get install -y software-properties-common
+            sudo add-apt-repository -y universe
+            sudo apt-get update
+            sudo apt install -y cmake \
+              ninja-build \
+              just \
+              libomp-dev \
+              libboost-dev \
+              libhdf5-serial-dev \
+              libopenblas-dev \
+              nlohmann-json3-dev
+            sudo apt-get install -y libhowardhinnant-date-dev
 
-    name: Run tests
-    runs-on: ubuntu-latest
+        - name: Checkout STIR
+          uses: actions/checkout@v4
+          with:
+            repository: UCL/STIR
+            ref: master
+            path: STIR
 
-    steps:
-      - uses: actions/checkout@v5
-        with: {submodules: recursive}
-      - name: strip environment.yml
-        run: |
-          cat environment.yml | grep -v "#.*\<\local\>" > temp-ci-environment.yml
-      - uses: conda-incubator/setup-miniconda@v3
-        with:
-          activate-environment: yardl
-          environment-file: temp-ci-environment.yml
-      - name: Install yardl
-        run: |
-          rm temp-ci-environment.yml
-          YARDL_DIR=${{github.workspace}}/yardl
-          mkdir ${YARDL_DIR}
-          YARDL_VERSION=0.6.5
-          wget --quiet "https://github.com/microsoft/yardl/releases/download/v${YARDL_VERSION}/yardl_${YARDL_VERSION}_linux_x86_64.tar.gz"
-          tar -xzf "yardl_${YARDL_VERSION}_linux_x86_64.tar.gz" -C "${YARDL_DIR}"
-          rm "yardl_${YARDL_VERSION}_linux_x86_64.tar.gz"
-          echo "${YARDL_DIR}" >> $GITHUB_PATH
+        - name: Checkout PETSIRD
+          uses: actions/checkout@v4
+          with:
+            repository: NikEfth/PETSIRD
+            ref: fix/cmake-export
+            path: PETSIRD
+            
+        - name: Checkout Yardl (main)
+          uses: actions/checkout@v4
+          with:
+            repository: microsoft/yardl
+            ref: main
+            path: yardl
+            
+        - name: Setup micromamba (yardl env)
+          uses: mamba-org/setup-micromamba@v2
+          with:
+            environment-file: yardl/environment.yml
+            activate-environment: yardl
+        
+        - name: Export CMake prefix path
+          run: |
+            echo "CMAKE_PREFIX_PATH=$CONDA_PREFIX;$CMAKE_PREFIX_PATH" >> $GITHUB_ENV
 
-      - name: Build model and compile
-        run: |
-          just
+        - name: Setup Go
+          uses: actions/setup-go@v5
+          with:
+            go-version: '1.22'
 
-      - name: Run
-        run: |
-          # This should get a usage message
-          # However, as this will return 1, we need to return "true", as otherwise the test would fail.
-          # So, this is therefore not a real test (except when you check the CI log)
-          STIR_PETSIRD_convertor || true
+        - name: Build and install Yardl
+          run: |
+            cd yardl/tooling/cmd/yardl
+            go build
+            mkdir -p "$HOME/.local/bin"
+            install -m 755 yardl $HOME/.local/bin/yardl
+            echo "$HOME/.local/bin" >> $GITHUB_PATH
+            "$HOME/.local/bin/yardl" --version
+
+        - name: Install just
+          run: |
+            sudo apt-get update
+            sudo apt-get install -y cmake ninja-build just
+
+        - name: Install PETSIRD Python dependencies
+          run: |
+            micromamba install -y -n yardl -f PETSIRD/environment.yml
+            micromamba install -y -n yardl -c conda-forge xtensor xtensor-blas openblas
+
+        - name: Generate PETSIRD sources (yardl) 
+          run: |
+            micromamba run -n yardl bash -lc "
+            export CC=/usr/bin/gcc
+            export CXX=/usr/bin/g++
+            
+            # Make conda packages visible to CMake
+            export CMAKE_PREFIX_PATH=\$CONDA_PREFIX:\$CMAKE_PREFIX_PATH
+            export CXXFLAGS=\"-I\$MAMBA_ROOT_PREFIX/envs/yardl/include \$CXXFLAGS\"
+
+            cd PETSIRD/model
+            just build
+            "
+        - name: Build PETSIRD C++
+          run: |
+            micromamba run -n yardl bash -lc "
+            cd PETSIRD/cpp
+            mkdir -p build 
+            cd build
+            
+            cmake .. \
+                -DCMAKE_BUILD_TYPE=Release \
+                -DCMAKE_PREFIX_PATH=\"\$CONDA_PREFIX\" \
+                -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/petsird-install"
+
+            cmake --build . --target install -j$(nproc)
+            "
+
+        - name: Fix yardl mistake
+          run: |
+            FILE="PETSIRD/cpp/generated/petsird/CMakeLists.txt"
+            echo "🔧 Fixing yardl-generated CMakeLists.txt (removing xtensor linkage)"
+            sed -i.bak \
+            -e '/^[[:space:]]*xtensor[[:space:]]*$/d' \
+            "$FILE"
+
+        - name: Configure STIR
+          run: |
+            # unset CONDA_PREFIX
+            # unset CONDA_DEFAULT_ENV
+            # unset CMAKE_PREFIX_PATH
+            # unset CPATH
+            # unset CXXFLAGS
+            # unset LDFLAGS
+            # unset LIBRARY_PATH
+            # unset LD_LIBRARY_PATH
+
+            export CC=/usr/bin/gcc
+            export CXX=/usr/bin/g++
+
+            mkdir -p build-stir
+            cd build-stir
+
+            cmake  ../STIR \
+              -DCMAKE_BUILD_TYPE=Release \
+              -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/stir-install" \
+              -DDISABLE_PETSIRD=ON \
+              -DDISABLE_HDF5=OFF \
+              -DDISABLE_NLOHMANN_JSON=OFF \
+              -DSTIR_OPENMP=ON
+
+        - name: Build STIR
+          run: |
+            cd build-stir
+            cmake --build . --target install -j$(nproc)
+
+        - name: Build STIR2PETSIRD
+          run: |
+            export CC=/usr/bin/gcc
+            export CXX=/usr/bin/g++
+            export CMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/stir-install:${GITHUB_WORKSPACE}/petsird-install"
+
+            cd cpp
+            mkdir -p build-stir2petsird
+            cd build-stir2petsird
+            
+            cmake .. \
+                -DCMAKE_BUILD_TYPE=Release
+            
+            cmake --build . -j$(nproc)
+
+
+
+      # # - name: Run
+      # #   run: |
+      # #     # This should get a usage message
+      # #     # However, as this will return 1, we need to return "true", as otherwise the test would fail.
+      # #     # So, this is therefore not a real test (except when you check the CI log)
+      # #     STIR_PETSIRD_convertor || true
